/*
generated by openai
 */

// Parse the input from stdin.
/* this is wrong
const input = await Deno.stdin.readText();
*/

// this is my code from day 1
import {readInput} from "./functions.ts";
const rucksacks = await readInput();

// and openai the rest
//const rucksacks = input.trim().split('\n');

// Define a function that computes the priority of an item type.
const getPriority = (itemType) => {
    if (itemType.toLowerCase() === itemType) {
        // Lowercase item types have priorities 1 through 26.
        return itemType.charCodeAt(0) - 'a'.charCodeAt(0) + 1;
    } else {
        // Uppercase item types have priorities 27 through 52.
        return itemType.charCodeAt(0) - 'A'.charCodeAt(0) + 27;
    }
};

// Compute the sum of the priorities of the common item types.
let result = 0;
for (const rucksack of rucksacks) {
    // Split the items into the first and second compartment.
    const n = rucksack.length / 2;
    const firstCompartment = new Set(rucksack.slice(0, n));
    const secondCompartment = new Set(rucksack.slice(n));

    // Find the common item types.
    const commonItemTypes = new Set(
        [...firstCompartment].filter((x) => secondCompartment.has(x)),
    );

    // Add the priority of each common item type to the result.
    for (const itemType of commonItemTypes) {
        result += getPriority(itemType);
    }
}

// Print the result.
console.log(result);
